language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - 5.2
  - hhvm
before_script:
  # Disable xdebug for speed.
  # NB: this should NOT be done for hhvm
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi

script: phpunit
