# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3.4-cli-stretch

    steps:
      - checkout
      - run: composer global require phpunit/phpunit
      - run: ~/.composer/vendor/bin/phpunit
